# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5123e10d1ccf9a7c25e32e0c486ee193d15eb7e9e0b4066a3b26e213774a12b08410d0ee0aa175dbb5577cc3503502645b1425c38cfdf38cd5c9b145e8d2fd3

test:
  secret_key_base: 714cd71dcb6592b33e2820da7f3554b2608fb09ec7217255f3d4ea5e42723cbb2472d9b7211b68238fdea2649a71938af47e4b03224329b140483e454bdb578d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
